version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-sid-node
    # 対象のブランチはmasterのみ
    branches:
      only:
        - master

    working_directory: ~/repo

    steps:
      # ソースコードのチェックアウト
      - checkout
      # キャッシュのリストア処理。
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
      # パッケージのインストール
      - run:
          name: package install
          command: npm install
      # デプロイに必要なfirebase-toolsのインストール
      - run: 
          name: firebase-tools install
          command: npm install -D firebase-tools
      # rulesのテストに使用するエミュレーターのセットアップ
      - run:
          name: emulators install
          command: ./node_modules/.bin/firebase setup:emulators:firestore
      # キャッシュの保存処理。
      - save_cache:
          paths:
            - node_modules
            - client/functions/node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
      #　デプロイの実行。build&testも含む
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase --project default deploy --token=$FIREBASE_TOKEN